#!/bin/bash

JAR="time"

JAVANLP="$JAVANLP_HOME/projects/core/classes:$JAVANLP_HOME/projects/more/classes:$JAVANLP_HOME/projects/research/classes:$JAVANLP_HOME/projects/core/lib/xom-1.2.6.jar:etc/models.jar"
CP="dist/$JAR.jar:etc/lib.jar:etc/scala-library.jar:etc/scala-compiler.jar:etc/jline.jar:etc/postgresql.jar:$JAVANLP:etc/jdom.jar:etc/joda-time.jar"
	
java -Xrunhprof:cpu=samples -cp $CP -server -Xmx2000M -ea time.DataProcessor $@

#if [ "$1" == "tempeval2" ]; then
#	java -cp $CP -server -Xmx2000M -ea time.TempEval2 $@
#elif [ "$1" == "timebank" ]; then
#	cd aux/timebank && ./toPsql.rb . data && cd ../.. &&\
#		java -cp $CP -server -Xmx2000M -ea time.NumberAnnotator timebank
#elif [ "$1" == "gutime" ]; then
#	if [ "$2" == "" ]; then
#		echo "Usage: `basename $0` gutime [annotate_directory]"
#		exit 1
#	fi
#	java -cp $CP -server -Xmx1000M -ea time.TimeAnnotator $2
#else
#	echo "Invalid dataset: $1"
#fi



