#!/bin/bash

#-----
# Manage Runs
#-----
function v {
	file=$1
	last=`ls out | sort -nr | head -n 1`
	vim out/$last/$file
}

function present() {
	last=`ls out | sort -nr | head -n 1`
	cd out/$last && ruby parses.rb && evince present.pdf; cd -
}

#-----
# Utilities
#-----
function r {
	make && ./run
}

function cmd {
	java -cp bin:etc/joda-time.jar:etc/scala-compiler.jar:etc/scala-library.jar:etc/jline.jar time.Time
}
