#!/usr/bin/ruby

require 'execrunner'

# -- DEPENDENCIES --
JAVANLP = "#{ENV['JAVANLP_HOME']}/projects/core/classes:#{ENV['JAVANLP_HOME']}/projects/more/classes:#{ENV['JAVANLP_HOME']}/projects/research/classes:#{ENV['JAVANLP_HOME']}/projects/core/lib/xom-1.2.6.jar"
JAR='time'
		
@timeDistribution = 1

# -- RUN --
env!( 
	# Program
	'java',
	# Runtime Options
	o('cp', 
		"dist/#{JAR}.jar:etc/lib.jar:etc/scala-library.jar:etc/scala-compiler.jar:etc/jline.jar:etc/postgresql.jar:#{JAVANLP}:etc/jdom.jar:etc/joda-time.jar:etc/math.jar"),
	o('Xrunhprof:cpu=samples'),
#	o('Xrunhprof:cpu=samples,heap=sites'),
	o('server'),
	o('Xmx1500M'),
	o('ea'),
	'time.Entry',

	run(
		# -- LEARNING --
		# <parser>
		selo(0, 'parser', 
			'CKYParser', 
			'SearchParser', 
			'PrimitivesOnly', 
			'ItsAlwaysFriday'),
		selo(3, 'kbestCKYAlgorithm',
			'0',   #G n^3 k^2 logk          naive
			'1',   #G n^3 k   logk          better mult
			'2',   #G n^3 + V k logk        combined mult/merge (special case of 3)
			'3'),  #G n^3 + |D_max| k logk  lazy evaluation
		o('rulePrior', 0.01),
		o('lexPrior', 0.01),
#		selo(2, 'smoothing',
#			'none',
#			'addOne',
#			'backoff'),
#		o('addOneCount', 0.1),
#		o('backoffFactor', 0.01),
		selo(1,'ckyCountType',
			'all',
			'bestAll',
			'bestRandom',
			'bestShallow'),
		selo(3,'CkyCountNormalization',
			'none',
			'uniform',
			'proportional',
			'distribution'),
		selo(@timeDistribution,'timeDistribution',
			'Point',
			'Multinomial',
			'Gaussian'),
		selo(@timeDistribution,'timeDistributionParams',
			'[]',
			'[1.0,0.5]',
			'[0.0,1.0]'),
		selo(0,'timeDistributionScope', 'Global', 'Local'),
		selo(0,'lexTagMethod',
			'PCFG',
			'CRF',
			'GOLD'),
		selo(0,'initMethod','uniform','random'),
#		o('freeNils'),
#		o('allowPartialTime'),
#		o('hardEM'),
		# <training>
		o('beam', 100),
		o('iters', 20),
		o('scoreBeam', 5),
		o('maxSearchTime', 10000),
		#<params>
		o('usetime'),

		#--AUX PARAMS--
		#(crf)
		o('crfKBest', 1000),
		selo(0,'crfFeatureFactory',
			'time.NeighboringWords',
			'edu.stanford.nlp.sequences.SuperSimpleFeatureFactory'),

		# -- EVALUATION --
#		o('exactMatchThreshold', 60*60*24), # a day
		o('exactMatchThreshold', 1),        # a second
		o('scoreGranularity', 60*60*24),  # a day
		o('c_overconstraining', 1.0),
		o('c_vagueness', 1.0),
#		o('guessRange'),
#		o('instantAsDay'),

		# -- DATA --
		selo(1,'data',
			'Toy',
			'English',
			'NYT'),
		o('retokenize'),
		o('collapseNumbers'),
		o('bucketNumbers'),

		o('train', '1-11'),
		o('dev', '11-16'),

		o('train', '0-142'),  # ENGLISH
		o('dev', '142-162'),  # ENGLISH
		o('test', '162-182'), # ENGLISH

		o('devTest', true),

		# -- DEBUG --
		#(general)
#		o('paranoid'),
		o('useSeed'),
		o('seed','42'),
		o('goldTagFile', 'aux/sentences-100-tagged'),
		o('badTimexes', 'aux/bad.txt'),
#		o('printAllParses'),
#		o('printFailures'),
#		o('cacheTemporalComputations',false),
		o('todoHacks'),
		o('reportK', 5),
		#(debug programs)
		selo(0,'runDebug',
			'none',
			'console',
			'crf',
			'goldTagRead'),

		# -- BOOTSTRAPING --
		#(exec options)
#		o('logDebug'),
		o('ignoreClasspath', "\"[#{ENV['JAVANLP_HOME']}/.*,etc/scala-.*.jar,etc/postgres.jar,etc/jdom.jar,etc/joda-time.jar]\""),
		#(logging)
		o('execDir', 'out'),
		o('execOutput', "\"psql://research@localhost:#{JAR}<what?why42?\""),
		#(data)
		o('execData', '"psql://research@localhost:data<what?why42?"'),
	nil),
nil)
