#!/usr/bin/ruby

require 'execrunner'

# -- DEPENDENCIES --
JAVANLP = "#{ENV['JAVANLP_HOME']}/projects/core/classes:#{ENV['JAVANLP_HOME']}/projects/research/classes"

# -- RUN --
env!( 
	# Program
	'java',
	# Runtime Options
	o('cp', 
		"dist/time.jar:etc/lib.jar:etc/scala-library.jar:etc/scala-compiler.jar:etc/postgresql.jar:#{JAVANLP}:etc/jdom.jar:etc/joda-time.jar"),
	o('Xrunhprof:cpu=samples'),
	o('Xmx500M'),
	o('server'),
	o('ea'),
	'time.Entry',

	run(
		# -- DATA --
		o('timebank', 'aux/relations-timebank-allclosed-nonones.info.xml'),
		o('tokenizationOpts', 'ptb3Escaping'),

		# -- BOOTSTRAPING --
		#(exec options)
#		o('logDebug'),
		o('ignoreClasspath', "\"[#{ENV['JAVANLP_HOME']}/.*,etc/scala-.*.jar,etc/postgres.jar,etc/jdom.jar,etc/joda-time.jar]\""),
		#(logging)
		o('execDir', 'out'),
		o('execOutput', '"psql://research@localhost:time<what?why42?"'),
		#(data)
		o('execData', '"psql://research@localhost:data<what?why42?"'),
	nil),
nil)
