#!/bin/sh

# Set these paths appropriately

BIN=/home/gabor/workspace/time/aux/tree-tagger/bin
CMD=/home/gabor/workspace/time/aux/tree-tagger/cmd
LIB=/home/gabor/workspace/time/aux/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
