#!/bin/sh

# Set these paths appropriately

BIN=/home/gabor/workspace/time/aux/tree-tagger/bin
CMD=/home/gabor/workspace/time/aux/tree-tagger/cmd
LIB=/home/gabor/workspace/time/aux/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/spanish-abbreviations
PARFILE=${LIB}/spanish-utf8.par
MWLFILE=${LIB}/spanish-mwls-utf8

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
