#!/bin/sh

# Set these paths appropriately

BIN=/home/gabor/workspace/time/aux/tree-tagger/bin
CMD=/home/gabor/workspace/time/aux/tree-tagger/cmd
LIB=/home/gabor/workspace/time/aux/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
