#!/bin/sh

# Set these paths appropriately

BIN=/home/gabor/workspace/time/aux/tree-tagger/bin
CMD=/home/gabor/workspace/time/aux/tree-tagger/cmd
LIB=/home/gabor/workspace/time/aux/tree-tagger/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/tokenize.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par
LEXFILE=${LIB}/english-lexicon.txt

$TOKENIZER -e -a $ABBR_LIST $* |
# remove empty lines
grep -v '^$' |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/IN\/that/\tIN/;'
